name: "Envoyer un Hello World !"
description: "Envoie un hello world par défaut, ou le message donné en input"
inputs:
  message:
    description: "Message à envoyer"
    required: true
    default: "Hello World"
  discord_webhook:
    description: "URL du webhook discord"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
