name: "Output d'un worfklow sur discord"
description: "Envoie sous forme de message embedded les résultats d'exécution d'un worfklow. Ceci via un webhook"
inputs: # On définit les inputs. c'est à dire, les informations données dans le with: lorsque le fichier de worfklow utilise cette action
  discord_webhook:
    description: "URL du webhook discord"
    required: true
  test_status:
    description: "Status du job précédent"
    required: true
  job_name:
    description: "Nom du job dont le webhook discord doit notifier"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
